services:
  foundry:
    image: ghcr.io/foundry-rs/foundry:stable
    volumes:
      - .:/workspace # Mount the current directory to /workspace inside the container
    working_dir: /workspace # Set the working directory to the mounted volume
    stdin_open: true
    tty: true
    command: sh
